name: rain
description: A new Flutter project.

publish_to: "none"

version: 1.1.7+18

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  dio: ^5.1.1
  isar: ^3.0.5
  intl: ^0.17.0
  shimmer: ^2.0.0
  iconsax: ^0.0.8
  timezone: ^0.9.1
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  flutter_glow: ^0.2.0
  url_launcher: ^6.1.10
  path_provider: ^2.0.14
  package_info_plus: ^3.0.3
  connectivity_plus: ^3.0.3
  isar_flutter_libs: ^3.0.5
  flutter_displaymode: ^0.5.0
  lat_lng_to_timezone: ^0.2.0
  custom_navigation_bar: ^0.8.2
  scrollable_positioned_list: ^0.3.5
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  isar_generator: ^3.0.5
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#182224"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#182224"
  image: "assets/icons/splash.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
